// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ChatPanel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"panel-chat\" class=\"panel\"><div class=\"panel-header\"><span>Reasoning & Chat</span> <span class=\"text-xs text-slate-500\">Subagents</span></div><!-- Subagent Autocomplete Badges --><div class=\"p-2 bg-slate-900 border-b border-slate-800 flex flex-wrap gap-1\" id=\"subagent-badges\"><!-- Populated dynamically via islands.js --></div><!-- Chat Feed & Thought Accordions --><div id=\"chat-feed\" class=\"chat-feed\"><div class=\"chat-bubble aris\">👋 Welcome to <strong>ARIS Web Interface</strong>. Enter a prompt below or type <code class=\"text-cyan-400\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("@subagent")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapters/ui/web/views/chat.templ`, Line: 18, Col: 127}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</code> to route directly to specialized agents.</div></div><!-- Parameter Controls Accordion -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ControlsSection().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Input Area --><div class=\"p-3 bg-slate-950 border-t border-slate-800 flex flex-col gap-2\"><textarea id=\"chat-input\" rows=\"2\" placeholder=\"Describe image or @director composition...\" class=\"input-control w-full resize-none font-sans text-sm\"></textarea><div class=\"flex justify-between items-center\"><button id=\"inpaint-btn\" class=\"btn btn-secondary text-xs\">Inpaint Area</button> <button id=\"chat-send-btn\" class=\"btn btn-primary text-xs\">Generate</button></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
