// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ControlsSection() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"controls-section\"><div class=\"flex justify-between items-center text-xs font-bold text-slate-400\"><span>Generation Parameters</span></div><!-- Aspect Ratio Buttons --><div class=\"form-group\"><label class=\"form-label\">Aspect Ratio</label><div class=\"flex gap-1\"><button class=\"btn btn-secondary text-xs flex-1 ratio-btn btn-primary\" data-ratio=\"1:1\">1:1</button> <button class=\"btn btn-secondary text-xs flex-1 ratio-btn\" data-ratio=\"16:9\">16:9</button> <button class=\"btn btn-secondary text-xs flex-1 ratio-btn\" data-ratio=\"9:16\">9:16</button> <button class=\"btn btn-secondary text-xs flex-1 ratio-btn\" data-ratio=\"4:3\">4:3</button> <button class=\"btn btn-secondary text-xs flex-1 ratio-btn\" data-ratio=\"21:9\">21:9</button></div></div><!-- Backend and Model Selector --><div class=\"grid grid-cols-2 gap-2\"><div class=\"form-group\"><label for=\"backend-select\" class=\"form-label\">Backend</label> <select id=\"backend-select\" class=\"select-control text-xs\"><option value=\"pollinations\">pollinations</option> <option value=\"comfyui\">comfyui</option> <option value=\"falai\">falai</option></select></div><div class=\"form-group\"><label for=\"model-select\" class=\"form-label\">Model</label> <select id=\"model-select\" class=\"select-control text-xs\"><option value=\"flux\">flux</option> <option value=\"flux-realism\">flux-realism</option> <option value=\"dall-e-3\">dall-e-3</option></select></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
